// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8HtKANJ2fB8pFZaYV6nJffkb7nD6gjnM',
    appId: '1:61441723641:web:2879ae3217752d7e0fe628',
    messagingSenderId: '61441723641',
    projectId: 'crypto-13977',
    authDomain: 'crypto-13977.firebaseapp.com',
    storageBucket: 'crypto-13977.firebasestorage.app',
    measurementId: 'G-98QFS7ZHP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRR6r4WnWJOp4VA8IH38gYOe6xi-E6x9U',
    appId: '1:61441723641:android:64f6bcc1c6c4a5510fe628',
    messagingSenderId: '61441723641',
    projectId: 'crypto-13977',
    storageBucket: 'crypto-13977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-_LFrqIWp2uPQkEcGbPVTM4UeNA-UVs',
    appId: '1:61441723641:ios:23059b29daddcb9d0fe628',
    messagingSenderId: '61441723641',
    projectId: 'crypto-13977',
    storageBucket: 'crypto-13977.firebasestorage.app',
    iosBundleId: 'com.example.agregatorKripto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8HtKANJ2fB8pFZaYV6nJffkb7nD6gjnM',
    appId: '1:61441723641:web:a028a3bcd8e77f660fe628',
    messagingSenderId: '61441723641',
    projectId: 'crypto-13977',
    authDomain: 'crypto-13977.firebaseapp.com',
    storageBucket: 'crypto-13977.firebasestorage.app',
    measurementId: 'G-L4Y9V8K9SD',
  );
}